# action.yml
name: 'LaTeX Releases'
description: 'Compile Latex/XeLatex files to GitHub releases'
branding:
  icon: file-text
  color: blue
inputs:
  tex_path:  # id of input
    description: 'Path of Tex File'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tex_path }}
